fmt:
  # Use a third-party repo since the official repo doesn't include tags.
  # https://github.com/rust-lang-nursery/docker-rust-nightly/issues/3
  image: instrumentisto/rust:nightly-2019-08-15
  before_script:
    - rustup component add rustfmt-preview
  script:
    - cargo fmt -- --check

# Each package is checked separately because of
# https://github.com/rust-lang/cargo/issues/5364
.check-crate:
  image: rust:1.37
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --manifest-path "$crate_dir"/Cargo.toml --all-targets --features strict

check-aether:
  extends: .check-crate
  variables:
    crate_dir: crates/aether

check-darksiders1-sys:
  extends: .check-crate
  variables:
    crate_dir: crates/darksiders1-sys

test:
  image: rust:1.37
  script:
    - cargo test
