# https://pre-commit.com/

repos:
  - repo: local
    hooks:
      - id: fix
        name: fix
        language: system
        files: '[.]rs$'
        entry: cargo fix --allow-staged
        pass_filenames: false

      - id: fmt
        name: fmt
        language: system
        files: '[.]rs$'
        entry: rustfmt
        pass_filenames: true

      # Each package is checked separately because of
      # https://github.com/rust-lang/cargo/issues/5364

      - id: check:aether
        name: check:aether
        language: system
        files: '[.]rs$'
        entry: cargo clippy --manifest-path crates/aether/Cargo.toml --all-targets --features strict
        pass_filenames: false

      - id: check:d3d11
        name: check:d3d11
        language: system
        files: '[.]rs$'
        entry: cargo clippy --manifest-path crates/d3d11/Cargo.toml --all-targets --features strict
        pass_filenames: false

      - id: check:darksiders1-sys
        name: check:darksiders1-sys
        language: system
        files: '[.]rs$'
        entry: cargo clippy --manifest-path crates/darksiders1-sys/Cargo.toml --all-targets --features strict
        pass_filenames: false

      - id: check:horseman
        name: check:horseman
        language: system
        files: '[.]rs$'
        entry: cargo clippy --manifest-path crates/horseman/Cargo.toml --all-targets --features strict
        pass_filenames: false

      - id: test
        name: test
        language: system
        files: '[.]rs$'
        entry: cargo test
        pass_filenames: false
