# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

edition = "2018"
error_on_line_overflow = false
error_on_unformatted = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
merge_imports = true
newline_style = "Unix"
overflow_delimited_expr = true
use_field_init_shorthand = true
wrap_comments = true
